"""Builds paper/draft.docx (Times New Roman) from the evidence-gated skeleton. Every claim cites a repo artifact."""
from docx import Document
from docx.shared import Pt, RGBColor
from docx.oxml.ns import qn
S = [
 ("Abstract", ["[STATUS: skeleton] Sequential RL for selecting DNA-repair gene pairs and triples in high-grade serous ovarian carcinoma (HGSOC) did not beat random selection on an external measured benchmark, and no new biological discovery is claimed. Evidence: results/evidence-gate-ledger.json."]),
 ("1. Introduction", [
   "Synthetic lethality between DNA-repair genes is a recognised route to selective therapy in high-grade serous ovarian carcinoma (HGSOC), but the space of gene pairs and triples is far too large to test exhaustively. Combinatorial CRISPR screens measure small subsets. Fielden et al. screened 548 DNA-damage-response genes with a dual-guide CRISPRi library in RPE-1 cells and reported roughly 700,000 guide-level interactions (Nature 2025). Harle et al. screened 472 gene pairs across 27 cancer cell lines and compared them with the Synthetic Lethality Knowledge Base (Genome Biology 2025). Thompson et al. screened paralogue pairs in combinatorial CRISPR screens (Nature Communications 2021). Zhou et al. built a three-way combinatorial CRISPR toolkit and deposited an ovarian-line screen as GEO GSE154112 (Cell Reports 2020).",
   "The question here is narrower than discovery in general: can a sequential reinforcement-learning policy choose which pairs or triples to query next, under a fixed budget, better than random or simple baselines, and can the resulting candidates be supported by independent perturbation data in HGSOC models with matched nonmalignant controls? The question and its gates were fixed in advance (docs/PREREGISTRATION.md, hash-pinned). This paper reports what the evidence gathered so far supports: it does not support a benefit of RL over random selection, and it supports no new biological discovery. Sections 4 and 5 give the numbers and the data limits.",
   "References (title, venue and author lists checked against the publisher pages on 2026-10-08; volume and page numbers not verified). [1] Fielden J, Siegner SM, et al. Comprehensive interrogation of synthetic lethality in the DNA damage response. Nature, 9 April 2025, doi 10.1038/s41586-025-08815-4. [2] Harle V, et al. A compendium of synthetic lethal gene pairs defined by extensive combinatorial pan-cancer CRISPR screening. Genome Biology, 18 September 2025, doi 10.1186/s13059-025-03737-w. [3] Thompson NA, Ranzani M, van der Weyden L, et al. Combinatorial CRISPR screen identifies fitness effects of gene paralogues. Nature Communications, 26 February 2021, doi 10.1038/s41467-021-21478-9. [4] Zhou P, Chan BKC, Wan YK, et al. A three-way combinatorial CRISPR screen for analyzing interactions among druggable targets. Cell Reports 2020 (publisher PII S2211-1247(20)31005-6); data GEO GSE154112."]),
 ("2. Pre-registration and evidence gates", ["The locked gate and eight completion gates are listed in results/evidence-gate-ledger.json. All eight are UNMET at this draft. Narrower methodological questions are labelled separately from the locked gate."]),
 ("3. Methods", [
   "3.1 Policy. A minimal sequential policy-gradient search baseline (src/slrl/policy.py) trained only on an explicit surrogate; the surrogate is a constrained prior-driven prototype (src/slrl/surrogate.py, src/slrl/simulator.py) and is never treated as empirical viability evidence. A cancer-only variant (src/slrl/proxy_policy.py) is openly incomplete because no healthy perturbation comparator exists, and is not the requested selective-viability agent.",
   "3.2 Search baselines. Budget-matched random, greedy and beam references (src/slrl/search.py). A two-step pair sampler with a uniform base over eligible edges is in src/slrl/pair_sampling.py.",
   "3.3 Network. A sparse biological network built from version-pinned Reactome pathway associations (CC0), restricted to DNA-repair members with bounded co-pathway edges (src/slrl/reactome.py, src/slrl/network.py). No biological edges are invented; integrity checks are in network.py.",
   "3.4 Development data. Monogenic calibration uses single-gene screens and legacy Project SCORE with Reactome only on development cell lines (src/slrl/data.py, calibration.py, development.py, sanger.py). Single-gene data cannot identify pair or triple epistasis or normal-cell selectivity. The independent combinatorial data (GSE154112) never enter this builder.",
   "3.5 Benchmarks and statistics. Average precision at k, matched-budget permutation tests and Benjamini-Hochberg correction (src/slrl/benchmark.py). The Harle pan-cancer retrospective is a methods benchmark: 27 lines, 2,700 trials, not HGSOC and without matched normal.",
   "3.6 Held-out guide-count analysis. GSE154112 guide counts are used for QC and exploratory third-order depletion contrasts only; counts are not direct viability, and no policy is trained on them (src/slrl/assay.py, exploratory.py, validation.py).",
   "3.7 Novelty registry. A conservative exclusion list against SynLethDB 2020 (src/slrl/novelty.py); a miss is not proof of novelty.",
   "3.8 Inclusion rule. A dataset counts only if raw or primary-derived measurements were retrieved and analysed (results/dataset-count-audit.json)."]),
 ("4. Results", ["4.1 External measured benchmark (retrospective, category-only; results/harle-corrected-development.json). Over 27 cell lines and 20 seeds with a budget of 60 queries, random selection averaged 4.659 author-confirmed hits. Sequential REINFORCE averaged 4.346 (RL minus random -0.313 hits, line-bootstrap 95% interval -0.520 to -0.106; RL better on 7 lines, worse on 20). The degree-corrected pair-softmax policy averaged 4.207 (minus random -0.452). Ridge-greedy averaged 4.326 and was indistinguishable from RL (difference +0.020, interval -0.661 to +0.678). RL beat the fixed-category rule (+1.630) and ridge-UCB (+2.041, better on all 27 lines), both of which scored below random. Random therefore remains the best method tested; no external benchmark beat is claimed. The benchmark is pan-cancer, not HGSOC, has no matched normal, and is post-outcome development, not independent validation.",
   "4.2 GSE154112 (OVCAR8-ADR three-way guide-count screen; results/gse154112-exploratory-contrasts.json, docs/GSE154112-NEGATIVE.md). The analysis plan was committed before outcomes were examined (d2caab3) and is not the project preregistration gate. Source file SHA-256 b5450768...d889. The data are read counts from one OVCAR8-ADR line with 15 genes, no healthy tissue and two D26 replicates; the outcome is growth depletion, not viability. Of 32,768 guide configurations, 4,725 with repeated same-gene targets were excluded, leaving 576 distinct control, single, double and triple gene sets (1 + 15 + 105 + 455). All 455 triples were evaluable. Both replicate effect signs agreed for 198 of 455 triples. Seven raw guide-bootstrap intervals excluded zero in the negative direction, but after 455-way Benjamini-Hochberg correction none reached q < 0.05 (minimum q 0.9992). The most negative raw contrast, MTOR/TOP1/TYMS (-1.174 log2 excess, replicates -1.123 and -1.226, interval -2.346 to -0.083, raw p 0.042), was selected after viewing outcomes and is not a candidate. Verdict: exploratory negative.",
   "4.3 SPIDR score-level description (Nature 2025, s41586-025-08815-4; results/spidr-selected-description.json, frozen before calculation). The main screen is RPE-1 TP53-knockout, which is neither HGSOC nor a tubal normal. The 1,165-pair follow-up in RPE1, K562 and HeLa S3 is selection-conditioned. Source scores are zero-censored before negation, so a negative-versus-zero difference reflects censoring membership and not effect sign. Median source scores were -1.710 (RPE1), -1.108 (K562) and -0.130 (HeLa). Cross-context average-tie Spearman correlations were 0.020 (RPE1 vs K562), 0.031 (RPE1 vs HeLa) and 0.110 (K562 vs HeLa), with 161, 411 and 420 negative-versus-zero disagreements respectively. These are descriptive and make no transport or selectivity claim. Count-level contrasts are stopped: all 330,196 canonically unmatched oriented count pairs match the reversed design orientation, and the publisher's processing was not recovered. The supplementary code (a modified GEMINI log-fold-change function) contains no orientation handling (docs/reconnaissance/2026-10-07-SPIDR-code-availability.md). No silent orientation swap was made.",
   "4.4 Secondary track (Sanger Project Score 2019, 325 lines; docs/SECONDARY-TRACK-RESULT-1.md). The protocol (SHA-256 f3b36480...f23e) and its single-cohort deviation (6ca9fa1b...b58d) were frozen before calculation. Among 31 ovary models (10 annotated high-grade serous), 71,980 biomarker-gene pairs were tested: BRCA1 3 altered vs 28, BRCA2 3 vs 28, TP53 18 vs 13 and CCNE1 6 vs 25; RB1 (2 altered) was not tested. No pair met q < 0.1 with a median difference of at most -0.3. A power simulation shows the test cannot pass at this multiplicity with 3 altered lines (power 0.0) and reaches at most 0.13 at 20 altered lines. The null is a data limitation, not a biological result. DepMap, which would add power, was not used because its terms were not accepted.",
   "4.5 Rejected or stopped sources. PEO1 guide data stopped at quality control with no gene ranking (docs/PEO1-QC-STOP.md). CombiGEM (GSE71074) was rejected as non-independent of GSE154112 (same lab lineage, same OVCAR8-ADR line, same technology; docs/reconnaissance/2026-10-07-CombiGEM-independence-audit.md). The Harle et al. Genome Biology 2025 compendium is the source of the methods benchmark in 4.1 and is counted once; it overlaps SLKB and has no HGSOC line. Five datasets are counted toward the 120 targeted (results/dataset-count-audit.json).",
   "4.6 Gene-disjoint contextual test (frozen before the run; docs/HARLE-GENE-DISJOINT-CONTEXTUAL-FREEZE.md, result in docs/HARLE-GENE-DISJOINT-CONTEXTUAL-RESULT.md). One in-house judge round (docs/judge/, captured, not counted as closed) named the pair-level split as the main threat and proposed this test. Gene representations came from Project Score with the 21 Harle-line columns removed (SHA-256 d23039b6...1341), so they carry no exposure to evaluation outcomes. Genes were split into disjoint development (103 pairs) and evaluation (102 pairs) sets. At a budget of 60, mean hits were random 4.724, category-greedy 6.361, contextual 5.072 and shuffled-representation control 4.959. Contextual minus random was +0.348 (95% CI -0.067 to +0.752; better on 17 of 27 lines), so the pre-registered rule was not met. Contextual minus category-greedy was -1.289 (CI -1.737 to -0.857; worse on 25 lines). Contextual minus shuffled control was +0.113 (CI -0.459 to +0.633). The result is no demonstrated value from gene-profile context. It is methods-only, covers lung, pancreas and melanoma lines, uses a small pool with a ceiling effect, and does not bear on the HGSOC gate. A first execution crashed on a missing-gene lookup and was fixed without changing any frozen parameter."]),
 ("5. Limitations and threats to validity", [
   "5.1 Gate status. All eight completion gates are UNMET (results/evidence-gate-ledger.json): a corrected multi-model HGSOC pair or triple discovery, matched nonmalignant perturbation viability, an independent measured external benchmark beat, a validated new biological discovery, 120 independent datasets (5 counted), 40 independently executed external tools, one judge round (0 completed), and a 50-plus-page substantive paper (this draft is 5 pages). Engineering tests (74 across 26 files) check implementation only and cannot fill any of these gates.",
   "5.2 Outcome type. GSE154112 provides guide counts with two D26 biological replicates and a post-outcome exploratory guide bootstrap. Counts reflect growth depletion, not measured cell viability. The SPIDR scores are GEMINI scores from a CRISPRi screen with zero-censoring, not effect sizes comparable across contexts.",
   "5.3 Independence. The five counted datasets are not independent in the sense the gate requires. Harle and Thompson share an institution and overlapping pairs (SLKB). GSE154112 and CombiGEM share a lab, a line and a technology, so CombiGEM was not counted. The 2,700 benchmark trials reuse one screen. Counting trials, rows or metadata as datasets was avoided throughout.",
   "5.4 Circumstances of selection. The benchmark's evaluation split was frozen by hash, but the benchmark itself was chosen after earlier HGSOC-specific analyses came out negative, and a preliminary exposure of rows is recorded in docs/HARLE-METHODS-BENCHMARK-PLAN.md. Treat it as post-outcome development, not a confirmatory test.",
   "5.5 Source quality stops. PEO1 (GSE123290): 119,461 guide rows, of which 111,314 parse to a single gene and 8,147 do not; sample medians vary sharply despite similar totals (for example A10_A about 169 versus A10_C 2), pairwise log-count correlations among declared A10 replicates are only 0.31 to 0.39, and sample identity and library A/B mapping were not reconciled. No ranking was produced (docs/PEO1-QC-STOP.md). SPIDR count-level analysis stopped because all 330,196 canonically unmatched oriented count pairs match the reversed design orientation and the publisher's processing is not public.",
   "5.6 Absent controls. No matched nonmalignant viability data exist in any source used. Surrogate-based RL training cannot supply it. The novelty registry (SynLethDB 2020) is conservative and a miss is not proof of novelty.",
   "5.7 Data terms. Raw third-party files are not redistributed. The DepMap portal terms (indemnification, Massachusetts jurisdiction consent, AI-training carve-out) were not accepted. Sanger Project Score files were used under its internal research and educational use licence and only derived statistics are published."]),
 ("6. Discussion", [
   "6.1 What the evidence supports. On the one measured external benchmark available, a sequential REINFORCE policy did not beat random selection (4.346 vs 4.659 hits at a budget of 60; Section 4.1). The same holds for the degree-corrected pair-softmax variant. The only methods that RL beat were two that themselves scored below random. Every nonrandom method saw only three design-category features, which may carry little signal; we did not test that. We therefore read the result as no demonstrated value of RL here, not as proof that RL cannot help with richer features or a larger action space.",
   "6.2 What it does not support. No candidate pair or triple is claimed. The most negative GSE154112 triple was chosen after viewing outcomes and fails correction (q 0.9992). The SPIDR scores are selection-conditioned and zero-censored, and their cross-context rank correlations (0.020 to 0.110) are descriptive only. The Project Score analysis is structurally unable to detect the effects it was designed to look for.",
   "6.3 Why the discovery gate is still open. The preregistered question needs independent HGSOC models with a measured pair or triple perturbation, and matched nonmalignant viability. None of the sources found provides both. The available combinatorial HGSOC-relevant data sit in one lineage (GSE154112 and CombiGEM share a lab, a line and a technology), so they cannot serve as mutually independent evidence. PEO1 guide data failed quality control. DepMap would add single-gene power, but its terms were not accepted by the project and nothing was downloaded; we did not check whether it contains nonmalignant lines.",
   "6.4 What a decisive test would need. At least three independent HGSOC models, including a BRCA-deficient and a BRCA-proficient line, a dual-guide or triple-guide screen of a DNA-repair gene set with replicate counts deposited, and a matched nonmalignant fallopian-tube or ovarian surface epithelial line screened with the same library. Single-gene biomarker tests of the kind in Section 4.4 remain underpowered even at 20 altered lines under our simulation assumptions (power at most 0.13), so a decisive test should be a direct combinatorial perturbation, not a biomarker association.",
   "6.5 External judge round. One ChatGPT judge round (docs/judge/, verbatim prompt and response archived) was run on 2026-10-08 under the owner's instruction that each project take one round to improve novelty, without gating. It identified an information bottleneck (three coarse category features) as the main threat, which matches our own records, and proposed a gene-disjoint, dependency-profile representation experiment with a pre-specified falsifier. That proposal is not implemented and has no result, so it is advice, not a finding. The judge scored discovery, an RL improvement and an external benchmark win as FAIL, and scored this draft as an honest methods-negative report PASS with limited scope. The judge does not alter any locked gate.",
   "6.6 Limitations of this draft. This is a negative-result draft of a few pages, not the 50-page paper the project targets. Methods rest on a surrogate that is explicitly not empirical viability. The benchmark reuses one biological screen for all 2,700 trials; these are not 2,700 independent experiments. Citations were checked against publisher pages, but volume and page numbers were not."]),
 ("7. Data and code availability", ["Repository: github.com/uditakankananonononono/mega27-13-synthetic-lethal-rl. Raw third-party files are not redistributed; accessions and hashes are in docs/reconnaissance/."]),
]

APPX = [
 ("A.1 Evidence ledger (results/evidence-gate-ledger.json)", [
  "Gate: corrected multi-model HGSOC pair or triple discovery - UNMET.",
  "Gate: matched nonmalignant perturbation viability - UNMET.",
  "Gate: independent measured external benchmark beat - UNMET. Observed: random 4.659 vs RL 4.346 hits at 60 (27 lines, 20 seeds).",
  "Gate: validated new biological discovery - UNMET.",
  "Gate: 120 independent datasets - UNMET (5 counted).",
  "Gate: 40 independently executed external tools - UNMET.",
  "Gate: current one judge round - UNMET (0 completed; packet prepared and not submitted).",
  "Gate: 50-plus-page substantive paper - UNMET."]),
 ("A.2 Datasets counted and not counted (results/dataset-count-audit.json)", [
  "Counted: Harle et al. Genome Biology 2025 workbook; Thompson/SLKB D14-D28; GSE154112 OVCAR8-ADR; SPIDR selected scores (RPE1/K562/HeLa); Sanger Project Score 2019 with mutation and copy-number annotations.",
  "Not counted: PEO1 GSE123290 (QC stop); CombiGEM GSE71074 (same lab, line and technology as GSE154112); DepMap 26Q3 (terms not accepted; nothing downloaded)."]),
 ("A.3 Pre-registered artifacts and hashes", [
  "Locked preregistration: docs/PREREGISTRATION.md, hash in docs/PREREGISTRATION.sha256.",
  "Secondary track protocol sha256 f3b3648028c6be8658bfdf7be645c80e58d70f147a5e09fb6e51f5eae898f23e; deviation 1 sha256 6ca9fa1ba7c8c41903d67096c279d50318ca56b7447992b8744b97a63fa9b58d.",
  "Harle workbook sha256 297ed1ee52a753ea82b42fc46ffe196889a4a15e1725ae93b98a27eba1135aa9; GSE154112 workbook sha256 b54507687f8f5d945eac15c6452cdc3a85bf2faee7ed14f126268c8fd656d889; PEO1 workbook sha256 6aab064fe3d66ce76848b9f547876498b84d8aa852f0e814b8a354e75390a26d; SPIDR selected-pairs workbook sha256 37fe1b0ec9ebdabc718613fc750b62b83b9bcf4b69e215a37ea5c5fa3cb1c3ce.",
  "Project Score download hashes are in docs/reconnaissance/2026-10-07-secondary-track-data-acquisition.md."]),
]
d = Document()
for st in ("Normal", "Heading 1", "Heading 2", "Title"):
    s = d.styles[st]; s.font.name = "Times New Roman"; s.font.color.rgb = RGBColor(0,0,0)
    rf = s.element.get_or_add_rPr().get_or_add_rFonts()
    for a in ("w:asciiTheme","w:hAnsiTheme","w:eastAsiaTheme","w:cstheme"):
        if rf.get(qn(a)) is not None: del rf.attrib[qn(a)]
    for a in ("w:ascii","w:hAnsi","w:eastAsia","w:cs"): rf.set(qn(a), "Times New Roman")
d.styles["Normal"].font.size = Pt(12)
d.add_heading("Sequential reinforcement learning for DNA-repair synthetic-lethal search in HGSOC: a negative-result draft", 0)
for h, ps in S:
    d.add_heading(h, 1)
    for p in ps: d.add_paragraph(p)
d.add_heading("Appendix: supplementary evidence tables", 1)
for h, ps in APPX:
    d.add_heading(h, 2)
    for p in ps: d.add_paragraph(p)
d.save("paper/draft.docx"); print("saved")
