"""Builds paper/draft.docx (Times New Roman) from the evidence-gated skeleton. Every claim cites a repo artifact."""
from docx import Document
from docx.shared import Pt, RGBColor
from docx.oxml.ns import qn
S = [
 ("Abstract", ["[STATUS: skeleton] Sequential RL for selecting DNA-repair gene pairs and triples in high-grade serous ovarian carcinoma (HGSOC) did not beat random selection on an external measured benchmark, and no new biological discovery is claimed. Evidence: results/evidence-gate-ledger.json."]),
 ("1. Introduction", ["[TODO] DNA-repair synthetic lethality in HGSOC; why combinatorial search; the pre-registered question (docs/PREREGISTRATION.md, hash-pinned)."]),
 ("2. Pre-registration and evidence gates", ["The locked gate and eight completion gates are listed in results/evidence-gate-ledger.json. All eight are UNMET at this draft. Narrower methodological questions are labelled separately from the locked gate."]),
 ("3. Methods", [
   "3.1 Policy. A minimal sequential policy-gradient search baseline (src/slrl/policy.py) trained only on an explicit surrogate; the surrogate is a constrained prior-driven prototype (src/slrl/surrogate.py, src/slrl/simulator.py) and is never treated as empirical viability evidence. A cancer-only variant (src/slrl/proxy_policy.py) is openly incomplete because no healthy perturbation comparator exists, and is not the requested selective-viability agent.",
   "3.2 Search baselines. Budget-matched random, greedy and beam references (src/slrl/search.py). A two-step pair sampler with a uniform base over eligible edges is in src/slrl/pair_sampling.py.",
   "3.3 Network. A sparse biological network built from version-pinned Reactome pathway associations (CC0), restricted to DNA-repair members with bounded co-pathway edges (src/slrl/reactome.py, src/slrl/network.py). No biological edges are invented; integrity checks are in network.py.",
   "3.4 Development data. Monogenic calibration uses single-gene screens and legacy Project SCORE with Reactome only on development cell lines (src/slrl/data.py, calibration.py, development.py, sanger.py). Single-gene data cannot identify pair or triple epistasis or normal-cell selectivity. The independent combinatorial data (GSE154112) never enter this builder.",
   "3.5 Benchmarks and statistics. Average precision at k, matched-budget permutation tests and Benjamini-Hochberg correction (src/slrl/benchmark.py). The Harle pan-cancer retrospective is a methods benchmark: 27 lines, 2,700 trials, not HGSOC and without matched normal.",
   "3.6 Held-out guide-count analysis. GSE154112 guide counts are used for QC and exploratory third-order depletion contrasts only; counts are not direct viability, and no policy is trained on them (src/slrl/assay.py, exploratory.py, validation.py).",
   "3.7 Novelty registry. A conservative exclusion list against SynLethDB 2020 (src/slrl/novelty.py); a miss is not proof of novelty.",
   "3.8 Inclusion rule. A dataset counts only if raw or primary-derived measurements were retrieved and analysed (results/dataset-count-audit.json)."]),
 ("4. Results", ["4.1 External measured benchmark (retrospective, category-only; results/harle-corrected-development.json). Over 27 cell lines and 20 seeds with a budget of 60 queries, random selection averaged 4.659 author-confirmed hits. Sequential REINFORCE averaged 4.346 (RL minus random -0.313 hits, line-bootstrap 95% interval -0.520 to -0.106; RL better on 7 lines, worse on 20). The degree-corrected pair-softmax policy averaged 4.207 (minus random -0.452). Ridge-greedy averaged 4.326 and was indistinguishable from RL (difference +0.020, interval -0.661 to +0.678). RL beat the fixed-category rule (+1.630) and ridge-UCB (+2.041, better on all 27 lines), both of which scored below random. Random therefore remains the best method tested; no external benchmark beat is claimed. The benchmark is pan-cancer, not HGSOC, has no matched normal, and is post-outcome development, not independent validation.",
   "4.2 GSE154112 (OVCAR8-ADR three-way guide-count screen; results/gse154112-exploratory-contrasts.json, docs/GSE154112-NEGATIVE.md). The analysis plan was committed before outcomes were examined (d2caab3) and is not the project preregistration gate. Source file SHA-256 b5450768...d889. The data are read counts from one OVCAR8-ADR line with 15 genes, no healthy tissue and two D26 replicates; the outcome is growth depletion, not viability. Of 32,768 guide configurations, 4,725 with repeated same-gene targets were excluded, leaving 576 distinct control, single, double and triple gene sets (1 + 15 + 105 + 455). All 455 triples were evaluable. Both replicate effect signs agreed for 198 of 455 triples. Seven raw guide-bootstrap intervals excluded zero in the negative direction, but after 455-way Benjamini-Hochberg correction none reached q < 0.05 (minimum q 0.9992). The most negative raw contrast, MTOR/TOP1/TYMS (-1.174 log2 excess, replicates -1.123 and -1.226, interval -2.346 to -0.083, raw p 0.042), was selected after viewing outcomes and is not a candidate. Verdict: exploratory negative.",
   "4.3 SPIDR score-level description (Nature 2025, s41586-025-08815-4; results/spidr-selected-description.json, frozen before calculation). The main screen is RPE-1 TP53-knockout, which is neither HGSOC nor a tubal normal. The 1,165-pair follow-up in RPE1, K562 and HeLa S3 is selection-conditioned. Source scores are zero-censored before negation, so a negative-versus-zero difference reflects censoring membership and not effect sign. Median source scores were -1.710 (RPE1), -1.108 (K562) and -0.130 (HeLa). Cross-context average-tie Spearman correlations were 0.020 (RPE1 vs K562), 0.031 (RPE1 vs HeLa) and 0.110 (K562 vs HeLa), with 161, 411 and 420 negative-versus-zero disagreements respectively. These are descriptive and make no transport or selectivity claim. Count-level contrasts are stopped: all 330,196 canonically unmatched oriented count pairs match the reversed design orientation, and the publisher's processing was not recovered. The supplementary code (a modified GEMINI log-fold-change function) contains no orientation handling (docs/reconnaissance/2026-10-07-SPIDR-code-availability.md). No silent orientation swap was made.",
   "4.4 Secondary track (Sanger Project Score 2019, 325 lines; docs/SECONDARY-TRACK-RESULT-1.md). The protocol (SHA-256 f3b36480...f23e) and its single-cohort deviation (6ca9fa1b...b58d) were frozen before calculation. Among 31 ovary models (10 annotated high-grade serous), 71,980 biomarker-gene pairs were tested: BRCA1 3 altered vs 28, BRCA2 3 vs 28, TP53 18 vs 13 and CCNE1 6 vs 25; RB1 (2 altered) was not tested. No pair met q < 0.1 with a median difference of at most -0.3. A power simulation shows the test cannot pass at this multiplicity with 3 altered lines (power 0.0) and reaches at most 0.13 at 20 altered lines. The null is a data limitation, not a biological result. DepMap, which would add power, was not used because its terms were not accepted.",
   "4.5 Rejected or stopped sources. PEO1 guide data stopped at quality control with no gene ranking (docs/PEO1-QC-STOP.md). CombiGEM (GSE71074) was rejected as non-independent of GSE154112 (same lab lineage, same OVCAR8-ADR line, same technology; docs/reconnaissance/2026-10-07-CombiGEM-independence-audit.md). The Genome Biology 2025 pan-cancer compendium was excluded for SLKB overlap and absence of HGSOC. Five datasets are counted toward the 120 targeted (results/dataset-count-audit.json)."]),
 ("5. Limitations", ["No matched nonmalignant viability data; no independent HGSOC multi-model dual-guide dataset; five datasets counted of the 120 targeted; no external judge round completed."]),
 ("6. Discussion", ["[TODO] What a future adequately powered, independent HGSOC screen would need."]),
 ("7. Data and code availability", ["Repository: github.com/uditakankananonononono/mega27-13-synthetic-lethal-rl. Raw third-party files are not redistributed; accessions and hashes are in docs/reconnaissance/."]),
]
d = Document()
for st in ("Normal", "Heading 1", "Title"):
    s = d.styles[st]; s.font.name = "Times New Roman"; s.font.color.rgb = RGBColor(0,0,0)
    rf = s.element.get_or_add_rPr().get_or_add_rFonts()
    for a in ("w:asciiTheme","w:hAnsiTheme","w:eastAsiaTheme","w:cstheme"):
        if rf.get(qn(a)) is not None: del rf.attrib[qn(a)]
    for a in ("w:ascii","w:hAnsi","w:eastAsia","w:cs"): rf.set(qn(a), "Times New Roman")
d.styles["Normal"].font.size = Pt(12)
d.add_heading("Sequential reinforcement learning for DNA-repair synthetic-lethal search in HGSOC: a negative-result draft", 0)
for h, ps in S:
    d.add_heading(h, 1)
    for p in ps: d.add_paragraph(p)
d.save("paper/draft.docx"); print("saved")
